# Generated by Django 5.0.4 on 2024-04-26 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_prompt_userprompts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPrompts',
            new_name='UserPrompt',
        ),
    ]
