# Generated by Django 5.0.4 on 2024-04-26 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_rename_userprompts_userprompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprompt',
            name='prompt',
        ),
        migrations.RemoveField(
            model_name='userprompt',
            name='user',
        ),
        migrations.AddField(
            model_name='userprompt',
            name='prompt_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.prompt'),
        ),
        migrations.AddField(
            model_name='userprompt',
            name='user_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.user'),
        ),
    ]
