# Generated by Django 5.0.4 on 2024-04-26 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_alter_prompt_execution_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='execution_time',
            field=models.TimeField(default=datetime.time(10, 54, 25, 421761)),
        ),
    ]
