# Generated by Django 5.0.4 on 2024-04-26 10:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_alter_prompt_execution_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='execution_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
