# Generated by Django 5.0.4 on 2024-04-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_alter_prompt_execution_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
