# Generated by Django 5.0.4 on 2024-04-27 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_prompt_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprompt',
            old_name='prompt_id',
            new_name='prompt',
        ),
        migrations.RenameField(
            model_name='userprompt',
            old_name='user_id',
            new_name='user',
        ),
    ]
